use anyhow::{bail, Result};
use std::path::PathBuf;

use crate::cache::get_cache_dir;
use crate::models::ModelInfo;
use crate::verify::verify_checksum;

pub fn bundle_model_for_wasm(info: &ModelInfo, dest_dir: &str) -> Result<()> {
    let cache_dir = get_cache_dir()?;
    let source = cache_dir.join(info.filename);

    if !source.exists() {
        bail!(
            "Model not found in cache. Download it first with: cargo xtask models download {}",
            info.name
        );
    }

    // Verify before bundling
    println!("Verifying model integrity...");
    if !verify_checksum(&source, info.sha256)? {
        bail!(
            "Model failed verification. Re-download with: cargo xtask models download {}",
            info.name
        );
    }

    let dest_dir = PathBuf::from(dest_dir);
    std::fs::create_dir_all(&dest_dir)?;

    let dest = dest_dir.join(info.filename);
    std::fs::copy(&source, &dest)?;

    println!("✓ Model bundled to: {}", dest.display());
    println!("  Size: {:.1} MB", info.size_bytes as f64 / 1_000_000.0);

    // Create README
    let readme_path = dest_dir.join("README.md");
    let readme_content = format!(
        "# Bundled ONNX Models\n\n\
        ## {}\n\n\
        - **Type**: {:?}\n\
        - **Size**: {:.1} MB\n\
        - **Input**: {}x{}\n\
        - **Description**: {}\n\
        - **Source**: {}\n\
        - **SHA-256**: {}\n\n\
        Generated by: `cargo xtask models bundle {}`\n",
        info.filename,
        info.model_type,
        info.size_bytes as f64 / 1_000_000.0,
        info.input_size,
        info.input_size,
        info.description,
        info.url,
        info.sha256,
        info.name
    );

    std::fs::write(&readme_path, readme_content)?;
    println!("✓ README created: {}", readme_path.display());

    Ok(())
}
